//----------- action types ------------//
export const MOVIE_DATA_LOADING = 'MOVIE_DATA_LOADING';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DATA_FAIL = 'GET_MOVIE_FAIL';
export const GET_RATING_FROM_DB = 'GET_RATING_FROM_DB';
export const GET_RATING_FROM_DB_FAIL = 'GET_RATING_FROM_DB_FAIL';

//export const GET_UPDATED_RATING = 'GET_UPDATED_RATING';
